import { Brand, Category, Product, ProductImage, ProductVariant, Banner, Testimonial } from '@/types/database';

// ==========================================
// BRANDS
// ==========================================
export const brands: Brand[] = [
  { id: 'b1', name: 'Yonex', slug: 'yonex', logo_url: null },
  { id: 'b2', name: 'Nivia', slug: 'nivia', logo_url: null },
  { id: 'b3', name: 'Cosco', slug: 'cosco', logo_url: null },
  { id: 'b4', name: 'SG', slug: 'sg', logo_url: null },
  { id: 'b5', name: 'SS', slug: 'ss', logo_url: null },
  { id: 'b6', name: 'BDM', slug: 'bdm', logo_url: null },
  { id: 'b7', name: 'Technoo', slug: 'technoo', logo_url: null },
  { id: 'b8', name: 'Dida', slug: 'dida', logo_url: null },
  { id: 'b9', name: 'Star Impact', slug: 'star-impact', logo_url: null },
  { id: 'b10', name: 'Aryan', slug: 'aryan', logo_url: null },
  { id: 'b11', name: 'ASI', slug: 'asi', logo_url: null },
  { id: 'b12', name: 'Stag', slug: 'stag', logo_url: null },
  { id: 'b13', name: 'Vector X', slug: 'vector-x', logo_url: null },
  { id: 'b14', name: 'Spartan', slug: 'spartan', logo_url: null },
  { id: 'b15', name: 'Puma', slug: 'puma', logo_url: null },
];

// ==========================================
// CATEGORIES
// ==========================================
export const categories: Category[] = [
  { id: 'c1', name: 'Cricket', slug: 'cricket', image_url: null, parent_id: null },
  { id: 'c2', name: 'Badminton', slug: 'badminton', image_url: null, parent_id: null },
  { id: 'c3', name: 'Football', slug: 'football', image_url: null, parent_id: null },
  { id: 'c4', name: 'Athletics', slug: 'athletics', image_url: null, parent_id: null },
  { id: 'c5', name: 'Basketball', slug: 'basketball', image_url: null, parent_id: null },
  { id: 'c6', name: 'Volleyball', slug: 'volleyball', image_url: null, parent_id: null },
  { id: 'c7', name: 'Table Tennis', slug: 'table-tennis', image_url: null, parent_id: null },
  { id: 'c8', name: 'Gym', slug: 'gym', image_url: null, parent_id: null },
  { id: 'c9', name: 'Shoes', slug: 'shoes', image_url: null, parent_id: null },
  { id: 'c10', name: 'Board Games', slug: 'board-games', image_url: null, parent_id: null },
  { id: 'c11', name: 'Indoor Games', slug: 'indoor-games', image_url: null, parent_id: null },
  { id: 'c12', name: 'Cones, Hurdles & Agility', slug: 'cones-hurdles-agility', image_url: null, parent_id: null },
  { id: 'c13', name: 'Sports Supports', slug: 'sports-supports', image_url: null, parent_id: null },
];

// ==========================================
// PRODUCTS
// ==========================================
const now = new Date().toISOString();

export const products: Product[] = [
  {
    id: 'p1',
    name: 'SG RSD Spark Kashmir Willow Cricket Bat',
    slug: 'sg-rsd-spark-kashmir-willow-cricket-bat',
    description: 'The SG RSD Spark is a premium Kashmir Willow cricket bat designed for all-round play. Excellent balance and thick edges for powerful strokes.',
    specifications: { weight: '1150-1200g', material: 'Kashmir Willow', handle: 'Short Handle', type: 'Cricket Bat' },
    category_id: 'c1',
    brand_id: 'b4',
    price: 2499,
    wholesale_price: 2000,
    stock_quantity: 45,
    sku: 'SG-RSD-SPARK',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p2',
    name: 'Yonex Nanoray Light 18i Badminton Racquet',
    slug: 'yonex-nanoray-light-18i-badminton-racquet',
    description: 'Yonex Nanoray Light 18i graphite badminton racquet. Ultra-lightweight and highly durable for fast, controlled swings.',
    specifications: { weight: '77g', tension: '20-30 lbs', flex: 'Flexible', material: 'Full Graphite' },
    category_id: 'c2',
    brand_id: 'b1',
    price: 2190,
    wholesale_price: 1800,
    stock_quantity: 60,
    sku: 'YNX-NR-18I',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p3',
    name: 'Nivia Storm Football Size 5',
    slug: 'nivia-storm-football-size-5',
    description: 'Nivia Storm Football is constructed with high-quality synthetic leather for excellent performance on hard grounds. Suitable for professional play.',
    specifications: { size: '5', material: 'Rubber', construction: 'Molded', stitching: 'Hand Stitched' },
    category_id: 'c3',
    brand_id: 'b2',
    price: 899,
    wholesale_price: 650,
    stock_quantity: 120,
    sku: 'NIV-STM-FB5',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p4',
    name: 'Cosco All Court Basketball Size 7',
    slug: 'cosco-all-court-basketball-size-7',
    description: 'Designed for both indoor and outdoor play, the Cosco All Court Basketball provides an exceptional grip and long-lasting durability.',
    specifications: { size: '7', material: 'Rubber', court: 'All Court' },
    category_id: 'c5',
    brand_id: 'b3',
    price: 1299,
    wholesale_price: 950,
    stock_quantity: 80,
    sku: 'COS-BB-ALL7',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p5',
    name: 'Yonex Mavis 350 Shuttlecocks (Pack of 6)',
    slug: 'yonex-mavis-350-shuttlecocks-pack-6',
    description: 'The standard for nylon shuttlecocks, providing a flight trajectory similar to feather shuttles with incredible durability.',
    specifications: { type: 'Nylon', speed: 'Medium', color: 'Yellow', pack_size: '6' },
    category_id: 'c2',
    brand_id: 'b1',
    price: 690,
    wholesale_price: 550,
    stock_quantity: 200,
    sku: 'YNX-MAVIS-350-6',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p6',
    name: 'SG Club Cricket Ball (Red)',
    slug: 'sg-club-cricket-ball-red',
    description: 'The SG Club is a high-quality two-piece cricket ball made from high-quality alum tanned leather. Ideal for club and school matches.',
    specifications: { material: 'Leather', pieces: 'Two-piece', color: 'Red', weight: '156g' },
    category_id: 'c1',
    brand_id: 'b4',
    price: 299,
    wholesale_price: 220,
    stock_quantity: 300,
    sku: 'SG-CLUB-BALL',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p7',
    name: 'Nivia Encounter Volleyball',
    slug: 'nivia-encounter-volleyball',
    description: 'Premium quality volleyball from Nivia. Soft touch technology ensures minimal impact on the arms while playing.',
    specifications: { size: '4', material: 'PU', type: 'Indoor/Outdoor' },
    category_id: 'c6',
    brand_id: 'b2',
    price: 749,
    wholesale_price: 600,
    stock_quantity: 150,
    sku: 'NIV-ENC-VB',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p8',
    name: 'Stag Championship Table Tennis Racquet',
    slug: 'stag-championship-table-tennis-racquet',
    description: 'Professional grade ITTF approved table tennis racquet. Great control and spin capabilities for intermediate to advanced players.',
    specifications: { rubber: 'Pimple In', speed: '8', spin: '7', control: '9' },
    category_id: 'c7',
    brand_id: 'b12',
    price: 1450,
    wholesale_price: 1100,
    stock_quantity: 50,
    sku: 'STAG-CHAMP-TT',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p9',
    name: 'Vector X Sprinter Running Shoes',
    slug: 'vector-x-sprinter-running-shoes',
    description: 'Lightweight and breathable running shoes designed for maximum comfort and speed. Features a shock-absorbing EVA sole.',
    specifications: { material: 'Mesh', sole: 'EVA', closure: 'Lace-Up', usage: 'Running' },
    category_id: 'c9',
    brand_id: 'b13',
    price: 1899,
    wholesale_price: 1450,
    stock_quantity: 90,
    sku: 'VX-SPRINT-SH',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p10',
    name: 'Cosco Dumbbell Set 10kg',
    slug: 'cosco-dumbbell-set-10kg',
    description: 'Ergonomically designed rubber coated hex dumbbells. Anti-roll design and comfortable grip for a perfect workout at home or gym.',
    specifications: { weight: '10kg (5kg x 2)', material: 'Cast Iron, Rubber Coated', shape: 'Hex' },
    category_id: 'c8',
    brand_id: 'b3',
    price: 1999,
    wholesale_price: 1600,
    stock_quantity: 40,
    sku: 'COS-DB-10KG',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p11',
    name: 'SS Ton Slasher English Willow Cricket Bat',
    slug: 'ss-ton-slasher-english-willow-cricket-bat',
    description: 'Premium English Willow cricket bat by SS. Handcrafted to provide a massive sweet spot for aggressive stroke play.',
    specifications: { willow: 'English Willow', weight: '1180-1250g', grade: 'Grade 3' },
    category_id: 'c1',
    brand_id: 'b5',
    price: 6999,
    wholesale_price: 5500,
    stock_quantity: 20,
    sku: 'SS-TON-SLASH',
    is_featured: true,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p12',
    name: 'Nivia Knee Support (Pack of 2)',
    slug: 'nivia-knee-support-pack-2',
    description: 'Provides excellent support and compression to the knee joint. Made from breathable elastic material for comfortable all-day wear.',
    specifications: { material: 'Elastic Nylon', size: 'Universal', pack: '2 Pieces' },
    category_id: 'c13',
    brand_id: 'b2',
    price: 499,
    wholesale_price: 350,
    stock_quantity: 250,
    sku: 'NIV-KNEE-SUP',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p13',
    name: 'Cosco Carrom Board Tournament',
    slug: 'cosco-carrom-board-tournament',
    description: 'Tournament quality carrom board with an exceptionally smooth playing surface and sturdy wooden frame for perfect rebounds.',
    specifications: { size: '32 x 32 inch', material: 'Assam Plywood', border: '3 x 1.5 inch' },
    category_id: 'c10',
    brand_id: 'b3',
    price: 2899,
    wholesale_price: 2200,
    stock_quantity: 15,
    sku: 'COS-CAR-TOURN',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p14',
    name: 'Star Impact Agility Cone Set (20 Pack)',
    slug: 'star-impact-agility-cone-set-20',
    description: 'Flexible and durable training cones ideal for field sports agility training. Bright colors for high visibility.',
    specifications: { count: '20', material: 'Flexible Plastic', colors: 'Assorted' },
    category_id: 'c12',
    brand_id: 'b9',
    price: 599,
    wholesale_price: 400,
    stock_quantity: 100,
    sku: 'SI-CONE-20',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p15',
    name: 'BDM Galaxy Plus Cricket Pads',
    slug: 'bdm-galaxy-plus-cricket-pads',
    description: 'High protection batting leg guards from BDM. Lightweight construction with high-density foam for superior impact resistance.',
    specifications: { type: 'Batting Pads', material: 'PU', protection: 'High Density Foam' },
    category_id: 'c1',
    brand_id: 'b6',
    price: 3499,
    wholesale_price: 2800,
    stock_quantity: 35,
    sku: 'BDM-GAL-PADS',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p16',
    name: 'Yonex Voltric 200 Tec Badminton Racquet',
    slug: 'yonex-voltric-200-tec-badminton-racquet',
    description: 'Tri-Voltage system racquet for exceptional power and great handling. Ideal for players looking to dominate with smashes.',
    specifications: { weight: '83g', flex: 'Stiff', material: 'Graphite+Tungsten' },
    category_id: 'c2',
    brand_id: 'b1',
    price: 3999,
    wholesale_price: 3100,
    stock_quantity: 25,
    sku: 'YNX-VOL-200T',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p17',
    name: 'Nivia Dominator Football Shoes',
    slug: 'nivia-dominator-football-shoes',
    description: 'Engineered for explosive speed and precise control. TPU outsole with conical studs for optimal traction on firm natural grass.',
    specifications: { sole: 'TPU Studs', upper: 'Synthetic Leather', surface: 'Firm Ground' },
    category_id: 'c9',
    brand_id: 'b2',
    price: 2299,
    wholesale_price: 1800,
    stock_quantity: 75,
    sku: 'NIV-DOM-FB-SH',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p18',
    name: 'SG Cricket Helmet Aeroshield 2.0',
    slug: 'sg-cricket-helmet-aeroshield-2',
    description: 'Advanced lightweight cricket helmet with hardened powder-coated steel grill for maximum protection and visibility.',
    specifications: { shell: 'Fiberglass', grill: 'Steel', vents: 'Multiple for airflow' },
    category_id: 'c1',
    brand_id: 'b4',
    price: 4999,
    wholesale_price: 3800,
    stock_quantity: 30,
    sku: 'SG-HELM-AERO',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p19',
    name: 'Cosco Gym Gloves Power Grip',
    slug: 'cosco-gym-gloves-power-grip',
    description: 'Premium weightlifting gloves with padded palms and wrist wraps for heavy lifting support and blister prevention.',
    specifications: { material: 'Leather/Spandex', closure: 'Velcro Strap', padding: 'Gel' },
    category_id: 'c8',
    brand_id: 'b3',
    price: 599,
    wholesale_price: 450,
    stock_quantity: 120,
    sku: 'COS-GLOV-PWR',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p20',
    name: 'SS Master Cricket Kit Bag',
    slug: 'ss-master-cricket-kit-bag',
    description: 'Spacious cricket kit bag with wheels. Made from heavy-duty nylon material with multiple compartments for organized storage.',
    specifications: { wheels: 'Yes', material: '1680D Nylon', type: 'Duffle/Wheelie' },
    category_id: 'c1',
    brand_id: 'b5',
    price: 2999,
    wholesale_price: 2300,
    stock_quantity: 40,
    sku: 'SS-BAG-MSTR',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p21',
    name: 'Stag Table Tennis Ball 3 Star (Pack of 6)',
    slug: 'stag-table-tennis-ball-3-star-pack-6',
    description: 'ITTF approved 3-star table tennis balls. Seamless construction for perfect roundness, even bounce, and long durability.',
    specifications: { size: '40mm+', material: 'Plastic', rating: '3 Star' },
    category_id: 'c7',
    brand_id: 'b12',
    price: 450,
    wholesale_price: 320,
    stock_quantity: 150,
    sku: 'STAG-TT-BALL3',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p22',
    name: 'Vector X Lace Up Football Shoes',
    slug: 'vector-x-lace-up-football-shoes',
    description: 'Durable football studs for everyday practice. The lace-up closure ensures a snug fit, while the PVC sole provides a steady grip.',
    specifications: { material: 'Synthetic', sole: 'PVC', surface: 'Grass/Turf' },
    category_id: 'c9',
    brand_id: 'b13',
    price: 1699,
    wholesale_price: 1200,
    stock_quantity: 85,
    sku: 'VX-LACE-FB-SH',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p23',
    name: 'Nivia Pro Basketball Shoes',
    slug: 'nivia-pro-basketball-shoes',
    description: 'High-top basketball shoes designed for ankle support. Features a phylon midsole for responsive cushioning on the court.',
    specifications: { type: 'High-Top', sole: 'Non-marking Rubber', closure: 'Lace-Up' },
    category_id: 'c9',
    brand_id: 'b2',
    price: 3299,
    wholesale_price: 2500,
    stock_quantity: 60,
    sku: 'NIV-PRO-BB-SH',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p24',
    name: 'Puma Track Pants Slim Fit',
    slug: 'puma-track-pants-slim-fit',
    description: 'Comfortable and stylish slim-fit track pants ideal for training and casual wear. Moisture-wicking fabric keeps you dry.',
    specifications: { material: 'Polyester Blend', fit: 'Slim', pockets: 'Zippered' },
    category_id: 'c4',
    brand_id: 'b15',
    price: 1499,
    wholesale_price: 1100,
    stock_quantity: 110,
    sku: 'PUMA-TRK-PNT',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p25',
    name: 'BDM Dasher Cricket Bat Kashmir Willow',
    slug: 'bdm-dasher-cricket-bat-kashmir-willow',
    description: 'An excellent entry-level Kashmir Willow bat with a traditionally shaped profile. Great value for tennis ball or light leather ball cricket.',
    specifications: { material: 'Kashmir Willow', size: 'Full Size', handle: 'Cane' },
    category_id: 'c1',
    brand_id: 'b6',
    price: 1799,
    wholesale_price: 1300,
    stock_quantity: 50,
    sku: 'BDM-DASH-BAT',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p26',
    name: 'Aryan Chess Board Set',
    slug: 'aryan-chess-board-set',
    description: 'Classic wooden folding chess board with hand-carved magnetic pieces. Perfect for indoor gaming and travel.',
    specifications: { material: 'Wood', type: 'Magnetic Folding', size: '12x12 inch' },
    category_id: 'c11',
    brand_id: 'b10',
    price: 799,
    wholesale_price: 550,
    stock_quantity: 65,
    sku: 'ARY-CHESS-WD',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p27',
    name: 'ASI Athletic Discus 1.5kg',
    slug: 'asi-athletic-discus-1-5kg',
    description: 'High-quality athletic training discus with a smooth rim and durable plastic side plates. Calibrated for precise weight.',
    specifications: { weight: '1.5kg', material: 'Steel Rim, Plastic Plates', type: 'Practice/Competition' },
    category_id: 'c4',
    brand_id: 'b11',
    price: 1299,
    wholesale_price: 900,
    stock_quantity: 20,
    sku: 'ASI-DISC-15',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'p28',
    name: 'Nivia Resistance Band Set',
    slug: 'nivia-resistance-band-set',
    description: 'Set of 5 color-coded resistance bands with different tension levels. Includes handles, door anchor, and ankle straps for full-body workouts.',
    specifications: { count: '5 Bands', material: 'Latex', accessories: 'Handles, Anchors' },
    category_id: 'c8',
    brand_id: 'b2',
    price: 899,
    wholesale_price: 650,
    stock_quantity: 95,
    sku: 'NIV-RES-BND5',
    is_featured: false,
    is_active: true,
    created_at: now,
    updated_at: now,
  },
];

// ==========================================
// PRODUCT IMAGES
// ==========================================
export const productImages: ProductImage[] = products.map((p) => ({
  id: `img-${p.id}`,
  product_id: p.id,
  image_url: `/images/products/${p.slug}.jpg`,
  alt_text: p.name,
  display_order: 0,
}));

// ==========================================
// PRODUCT VARIANTS
// ==========================================
export const productVariants: ProductVariant[] = [
  // Shoe variants (p9 - Vector X Sprinter)
  { id: 'v1', product_id: 'p9', variant_type: 'Size', variant_value: 'UK 7', sku: 'VX-SPRINT-SH-7', price_override: null, stock_quantity: 30 },
  { id: 'v2', product_id: 'p9', variant_type: 'Size', variant_value: 'UK 8', sku: 'VX-SPRINT-SH-8', price_override: null, stock_quantity: 40 },
  { id: 'v3', product_id: 'p9', variant_type: 'Size', variant_value: 'UK 9', sku: 'VX-SPRINT-SH-9', price_override: null, stock_quantity: 20 },
  
  // Shoe variants (p17 - Nivia Dominator)
  { id: 'v4', product_id: 'p17', variant_type: 'Size', variant_value: 'UK 8', sku: 'NIV-DOM-FB-SH-8', price_override: null, stock_quantity: 35 },
  { id: 'v5', product_id: 'p17', variant_type: 'Size', variant_value: 'UK 9', sku: 'NIV-DOM-FB-SH-9', price_override: null, stock_quantity: 40 },

  // Cricket Bat variants (p1 - SG RSD Spark)
  { id: 'v6', product_id: 'p1', variant_type: 'Weight', variant_value: 'Light (1150g)', sku: 'SG-RSD-SPARK-L', price_override: null, stock_quantity: 15 },
  { id: 'v7', product_id: 'p1', variant_type: 'Weight', variant_value: 'Medium (1200g)', sku: 'SG-RSD-SPARK-M', price_override: null, stock_quantity: 30 },

  // Clothing (p24 - Puma Track Pants)
  { id: 'v8', product_id: 'p24', variant_type: 'Size', variant_value: 'M', sku: 'PUMA-TRK-PNT-M', price_override: null, stock_quantity: 50 },
  { id: 'v9', product_id: 'p24', variant_type: 'Size', variant_value: 'L', sku: 'PUMA-TRK-PNT-L', price_override: null, stock_quantity: 40 },
  { id: 'v10', product_id: 'p24', variant_type: 'Size', variant_value: 'XL', sku: 'PUMA-TRK-PNT-XL', price_override: null, stock_quantity: 20 },
];

// ==========================================
// BANNERS
// ==========================================
export const banners: Banner[] = [
  {
    id: 'ban1',
    title: 'Gear Up for the Season',
    image_url: '/images/banners/cricket-banner.jpg',
    link_url: '/products/cricket',
    is_active: true,
    display_order: 1,
  },
  {
    id: 'ban2',
    title: 'Smash Your Goals',
    image_url: '/images/banners/badminton-banner.jpg',
    link_url: '/products/badminton',
    is_active: true,
    display_order: 2,
  },
  {
    id: 'ban3',
    title: 'Stay Fit, Stay Active',
    image_url: '/images/banners/gym-banner.jpg',
    link_url: '/products/gym',
    is_active: true,
    display_order: 3,
  },
];

// ==========================================
// TESTIMONIALS
// ==========================================
export const testimonials: Testimonial[] = [
  {
    id: 't1',
    customer_name: 'Rahul Sharma',
    content: 'Anand Sports is my go-to place for cricket gear. They have the best collection of bats and the wholesale pricing makes it incredibly affordable.',
    rating: 5,
    image_url: null,
    is_active: true,
  },
  {
    id: 't2',
    customer_name: 'Priya Patel',
    content: 'Bought a Yonex badminton racquet from them. Genuine product and fast delivery. Very satisfied with the customer service.',
    rating: 5,
    image_url: null,
    is_active: true,
  },
  {
    id: 't3',
    customer_name: 'Amit Kumar',
    content: 'Great selection of footballs and studs. I placed a bulk order for our local club and got an amazing discount.',
    rating: 4,
    image_url: null,
    is_active: true,
  },
  {
    id: 't4',
    customer_name: 'Sneha Reddy',
    content: 'Ordered fitness bands and dumbbells for my home gym. The quality is top-notch and exactly as described on the website.',
    rating: 5,
    image_url: null,
    is_active: true,
  },
  {
    id: 't5',
    customer_name: 'Vikram Singh',
    content: 'The best sports shop! I have been buying from Anand Sports for years. Highly reliable and always stocking the latest sports equipment.',
    rating: 5,
    image_url: null,
    is_active: true,
  },
];
